CREATE DATABASE DB_FASTFOOD
--ON PRIMARY 
--(
--	NAME = DB_FASTFOOD_PRIMARY,
--	FILENAME = '',
--	SIZE = 10MB,
--	MAXSIZE = 25MB,
--	FILEGROWTH = 15%
--)
--LOG ON
--(
--	NAME = DB_FASTFOOD_LOG,
--	FILENAME = '',
--	SIZE = 5MB,
--	MAXSIZE = 15MB,
--	FILEGROWTH = 15%
--)

USE DB_FASTFOOD
GO

CREATE TABLE ROLES
( 
	ROLEID INT IDENTITY(1, 1),
	ROLENAME NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_ROLES PRIMARY KEY (ROLEID)
)
ALTER TABLE ROLES
ADD CONSTRAINT DF_ROLENAME DEFAULT ( N'Khách Hàng') FOR ROLENAME

SELECT * FROM ROLES

INSERT ROLES
VALUES
(N'Admin'),
(N'Khách Hàng')

CREATE TABLE USERS
(
	USERID INT IDENTITY (1, 1),
	FULLNAME NVARCHAR (100),
	PHONE VARCHAR(11) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	DAYOFBIRTH DATE,
	USERADDRESS NVARCHAR (255),
	USERPASSWORD VARCHAR (50) NOT NULL,
	ROLEID INT NOT NULL,
	CREATEDAT DATE NOT NULL,
	UPDATEDAT DATE,
	CONSTRAINT PK_USERS PRIMARY KEY (USERID),
	CONSTRAINT FK_USERS_FOLES FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
)

ALTER TABLE USERS
ADD CONSTRAINT DF_CREATEDAT DEFAULT (CURRENT_TIMESTAMP) FOR CREATEDAT

-- LOG IN
--- EMAIL/PHONE

SELECT * FROM USERS

SET DATEFORMAT DMY
INSERT INTO USERS
VALUES
( N'Nguyễn Văn', '0317638299', 'vn20@gmail.com', '20/04/2003', N'Gia Lai', 'van12312', 1, '15/11/2023', NULL), 
( N'Đinh Thị Tuyết Chinh', '0312345678', 'dttc2004@gmail.com', '20/04/2003', N'Gia Lai', 'van1212', 2, '15/10/2023', NULL) 

CREATE TABLE PRODUCTTYPE
(
	PROD_TYPE_ID INT IDENTITY(1, 1),
	PROD_TYPE_NAME VARCHAR(50),
	CONSTRAINT PK_PROD_TYPE PRIMARY KEY (PROD_TYPE_ID)
)

SELECT * FROM PRODUCTTYPE
INSERT INTO PRODUCTTYPE
VALUES
('Drink'),
('Combo'),
('Pizza'),
('Snack'),
('Fried chicken')

CREATE TABLE PRODUCTS
(
	PRODUCTID INT IDENTITY(1, 1),
	PRODUCTNAME NVARCHAR(MAX) NOT NULL,
	PRODUCTDESCRIPTION NVARCHAR(MAX), -- Mô tả
	PRICE MONEY NOT NULL,
	PICTURE NVARCHAR(MAX),
	CREATED_AT_OF_PROD DATE NOT NULL,
	UPDATED_AT_OF_PROD DATE,
	PROD_TYPE_ID INT,
	CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCTID),
	CONSTRAINT FK_PRODUCTS_PRODUCTTYPE FOREIGN KEY (PROD_TYPE_ID) REFERENCES PRODUCTTYPE(PROD_TYPE_ID)

)
ALTER TABLE PRODUCTS
ADD CONSTRAINT DF_CREATEDATOFPRODUCT DEFAULT (CURRENT_TIMESTAMP) FOR CREATED_AT_OF_PROD

SET DATEFORMAT DMY
INSERT INTO PRODUCTS
VALUES
('PEPSI REGULAR', N'PEPSI REGULAR', '12.000', 'PepsiRegular.png', '15/11/2023', NULL, 1),
('PEPSI LARGE', N'PEPSI LARGE', '17.000', 'PepsiLarge.png', '15/11/2023', NULL, 1),
('7 UP REGULAR', N'7 UP REGULAR', '12.000', '7UpRegular.png', '15/11/2023', NULL, 1),
('7 UP LARGE', N'7 UP LARGE', '17.000', '7UpLarge.png', '15/11/2023', NULL, 1),
('1PC CHILLI CHICKEN', N'1PC CHILLI CHICKEN', '30.000', 'MotGaSotCay.png',  '15/11/2023', NULL, 5) 

SELECT * FROM PRODUCTS
DROP TABLE PRODUCTS

CREATE TABLE ORDERS
(
	ORDERID INT IDENTITY(1, 1),
	USERID INT,
	TOTAL_PRICE MONEY,
	STATUS_OF_ORDER NVARCHAR(100),
	CONSTRAINT PK_ORDERS PRIMARY KEY (ORDERID),
	CONSTRAINT FK_ORDERS_ORDER FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID)
)

INSERT INTO ORDERS
VALUES
(1, 0, 'Pending ...')
SELECT * FROM ORDERS

CREATE TABLE ORDERDETAIL
(
	ORDERID INT NOT NULL,
	PRODUCTID INT NOT NULL,
	NOTES NVARCHAR(MAX),
	QUANTITY INT,
	PRICE MONEY,
	CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ORDERID, PRODUCTID),
	CONSTRAINT FK_ORDERDETAIL_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID),
	CONSTRAINT FK_ORDERDETAIL_ORDER FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID)
)
DROP TABLE ORDERDETAIL
INSERT INTO ORDERDETAIL
VALUES
(1,2, N'Little of sugar', 1, (SELECT PRICE FROM PRODUCTS WHERE PRODUCTID = 2))
SELECT * FROM ORDERDETAIL

CREATE TABLE CART
(
	CARTID INT IDENTITY(1, 1),
	PRODUCTID INT,
	USERID INT,
	QUANTITY INT,
	PRICE MONEY,
	NOTES NVARCHAR(MAX),
	CONSTRAINT PK_CART PRIMARY KEY (CARTID),
	CONSTRAINT FK_CART_PRODUCTS FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID),
	CONSTRAINT FK_CART_USERS FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

INSERT INTO CART
VALUES
(2, 1, 1,(SELECT PRICE FROM PRODUCTS WHERE PRODUCTID = 2),'' )

SELECT * FROM CART

CREATE TABLE CONTACT
(
	CONTACT_ID INT IDENTITY (1, 1),
	FULLNAME NVARCHAR (100),
	PHONE VARCHAR(11) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	COMMENTS NVARCHAR(MAX),
	CONSTRAINT PK_CONTACT PRIMARY KEY (CONTACT_ID)
)

SELECT * FROM CONTACT